First PR
apomelitos/typescript-test pull request #1
Opened 2022-02-02 09:39 UTC by apomelitos

2022-02-02 14:34 UTC, TheForsakenSpirit requested changes

2022-02-02 14:34 UTC, TheForsakenSpirit commented on my-app/src/components/EvolutionsList.tsx
> +  const getArrayFromRecursiveObject = (obj: EvolutionChain): Array<EvolutionChain> => {
```suggestion
  const getArrayFromRecursiveObject = (obj: EvolutionChain): EvolutionChain[] => {
```

2022-02-02 14:34 UTC, TheForsakenSpirit commented on my-app/src/components/EvolutionsList.tsx
> +  };
Move out from render function

2022-02-02 14:34 UTC, TheForsakenSpirit commented on my-app/src/components/EvolutionsList.tsx
> +    const { chain } = (await evolutionResponse.json()) as { chain: EvolutionChain };
Use [type guard](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) to cast types.

2022-02-02 14:34 UTC, TheForsakenSpirit commented on my-app/src/components/EvolutionsList.tsx
> +    }
use `Promise.all` and map to make paralleled query.

2022-02-02 14:34 UTC, TheForsakenSpirit commented on my-app/src/components/EvolutionsList.tsx
> +          <li key={idx}>
try to generate key from item.

2022-02-02 14:34 UTC, TheForsakenSpirit commented on my-app/src/components/Pagination.tsx
> +
Remove commented code from pr

2022-02-02 14:34 UTC, TheForsakenSpirit commented on my-app/src/components/Pagination.tsx
> +  //   if (t)
remove

2022-02-03 12:01 UTC, TheForsakenSpirit requested changes

2022-02-03 12:01 UTC, TheForsakenSpirit commented on src/components/EvolutionsList.tsx
> +  }, [fetchEvolutions]);
Just move this callback to `useEffect`

2022-02-03 12:01 UTC, TheForsakenSpirit commented on src/components/EvolutionsList.tsx
> +        }
use not generic type guard.

2022-02-03 12:01 UTC, TheForsakenSpirit commented on src/components/PokemonCard.tsx
> +        const data: unknown = (await response.json()) as PokemonType;
`unknown` or `PokemonType`?

2022-02-03 12:01 UTC, TheForsakenSpirit commented on src/components/PokemonCard.tsx
> +        if (!isTypeOf<PokemonType>(data, 'base_experience')) {
use not generic type guard

2022-02-03 12:01 UTC, TheForsakenSpirit commented on src/components/PokemonDetails.tsx
> +        if (!isTypeOf<PokemonType>(data, 'base_experience')) {
use not generic type guard

2022-02-03 12:01 UTC, TheForsakenSpirit commented on src/utils/helpers.ts
> +  return value instanceof Object && key in value;
`key in value` potential dangerous condition.
If value = null it will throw an exception.

2022-02-03 12:12 UTC, apomelitos commented on src/components/EvolutionsList.tsx
> +  }, [fetchEvolutions]);
Moved

2022-02-03 12:16 UTC, apomelitos commented on src/components/EvolutionsList.tsx
> +        }
Replaced all type guards in ([ce3421c](https://github.com/apomelitos/typescript-test/pull/1/commits/ce3421c857d5f068257ec0ce7cfc7a6aa444006a)) commit

2022-02-03 13:51 UTC, TheForsakenSpirit approved these changes

2022-02-03 13:58 UTC, merged